---
title: "Smart Week 2"
author: "Christian Duenas"
date: "4/6/2021"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(learnr)

# Load in the datasets

curr_dir <- dirname(dirname(dirname(getwd())))

load( paste0(curr_dir, "/data/long.RData") )
load( paste0(curr_dir, "/data/wide.RData") )
#load("ucrstats/data/long.RData")
```




## Tidyverse


```{r tidyverse, exercise = TRUE}
library(tidyr)
wide %>% tidyr::pivot_longer( , names_to = c(), names_sep=) %>% 
  pivot_wider(names_from = , values_from = ) -> new_long 
```


```{r tidyverse-solution}
# Tidyr method
library(tidyr)
wide %>% tidyr::pivot_longer( `v1/mean`:`v4/median`, names_to = c("time","stat"), names_sep="/") %>% # pivot longer to separate vs from stat
  pivot_wider(names_from = stat, values_from = value) -> new_long # Recreate stats using pivot wider

# head(new_long)

# Verify dataframes are equal
# all.equal(new_long, long)
```


## Base R

```{r base_r, exercise = TRUE}

```


```{r base_r-solution}
# Covert using as.data.frame
in_data <- as.data.frame(wide) 
# Use reshape to covert from wide to long
to_long <- reshape(data = in_data, direction = "long", idvar = "ID1", sep ="/", v.names = c("mean", "sd", "median"), timevar = "time", times =c("v1", "v2", "v3", "v4"),
        varying = list(grep("mean", colnames(in_data), value=T), grep("sd", colnames(in_data), value=T), grep("median", colnames(in_data), value=T)))
# remove the rownames 
rownames(to_long) <- c()
# to_long

# to_long %>% filter(ID1 == "Ad9131ee9") # check
```

